-- Seed stock from the previous in-memory array in api/admin/stock.js.
-- INSERT OR IGNORE so re-running never clobbers live counts.
INSERT OR IGNORE INTO stock (color, size, stock) VALUES
  ('White-Blue', 'Small', 0),
  ('White-Blue', 'Medium', 3),
  ('White-Blue', 'Large', 3),
  ('White-Blue', 'XL', 2),
  ('White-Blue', 'XXL', 2),
  ('Black-Pink', 'Small', 0),
  ('Black-Pink', 'Medium', 3),
  ('Black-Pink', 'Large', 3),
  ('Black-Pink', 'XL', 2),
  ('Black-Pink', 'XXL', 2),
  ('Black-Red', 'Small', 0),
  ('Black-Red', 'Medium', 3),
  ('Black-Red', 'Large', 3),
  ('Black-Red', 'XL', 2),
  ('Black-Red', 'XXL', 2),
  ('Cream-Red', 'Small', 0),
  ('Cream-Red', 'Medium', 2),
  ('Cream-Red', 'Large', 2),
  ('Cream-Red', 'XL', 1),
  ('Cream-Red', 'XXL', 0),
  ('Grey-Yellow', 'Small', 1),
  ('Grey-Yellow', 'Medium', 2),
  ('Grey-Yellow', 'Large', 2),
  ('Grey-Yellow', 'XL', 1),
  ('Grey-Yellow', 'XXL', 0),
  ('Mint Green-Teal', 'Small', 0),
  ('Mint Green-Teal', 'Medium', 2),
  ('Mint Green-Teal', 'Large', 2),
  ('Mint Green-Teal', 'XL', 1),
  ('Mint Green-Teal', 'XXL', 0),
  ('Pale Blue-Orange', 'Small', 0),
  ('Pale Blue-Orange', 'Medium', 2),
  ('Pale Blue-Orange', 'Large', 2),
  ('Pale Blue-Orange', 'XL', 1),
  ('Pale Blue-Orange', 'XXL', 0),
  ('Grey Sleeveless-Yellow', 'Small', 1),
  ('Grey Sleeveless-Yellow', 'Medium', 2),
  ('Grey Sleeveless-Yellow', 'Large', 2),
  ('Grey Sleeveless-Yellow', 'XL', 1),
  ('Grey Sleeveless-Yellow', 'XXL', 1),
  ('Pale Blue Sleeveless-Green', 'Small', 1),
  ('Pale Blue Sleeveless-Green', 'Medium', 2),
  ('Pale Blue Sleeveless-Green', 'Large', 2),
  ('Pale Blue Sleeveless-Green', 'XL', 1),
  ('Pale Blue Sleeveless-Green', 'XXL', 1);
